/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Snp
 */
public class CadastroUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public CadastroUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cadastro = new javax.swing.JLabel();
        NomeJLabel = new javax.swing.JLabel();
        TextNome = new javax.swing.JTextField();
        CpfJLabel = new javax.swing.JLabel();
        TextCpf = new javax.swing.JTextField();
        TelefoneJLabel = new javax.swing.JLabel();
        TextTelefone = new javax.swing.JTextField();
        TextEmail = new javax.swing.JTextField();
        EmailJLabel = new javax.swing.JLabel();
        EnderecoJLabel = new javax.swing.JLabel();
        TextEndereco = new javax.swing.JTextField();
        BairrojLabel = new javax.swing.JLabel();
        TextBairro = new javax.swing.JTextField();
        SenhaJLabel = new javax.swing.JLabel();
        TextSenha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Nome1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cadastro.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Cadastro.setForeground(new java.awt.Color(255, 255, 255));
        Cadastro.setText("Cadastro");
        getContentPane().add(Cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        NomeJLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        NomeJLabel.setForeground(new java.awt.Color(255, 255, 255));
        NomeJLabel.setText("Nome ");
        getContentPane().add(NomeJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        TextNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNomeActionPerformed(evt);
            }
        });
        getContentPane().add(TextNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 340, 40));

        CpfJLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        CpfJLabel.setForeground(new java.awt.Color(255, 255, 255));
        CpfJLabel.setText("CPF");
        getContentPane().add(CpfJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        TextCpf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCpfActionPerformed(evt);
            }
        });
        getContentPane().add(TextCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 340, 40));

        TelefoneJLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        TelefoneJLabel.setForeground(new java.awt.Color(255, 255, 255));
        TelefoneJLabel.setText("Telefone");
        getContentPane().add(TelefoneJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        TextTelefone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(TextTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 340, 40));

        TextEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEmailActionPerformed(evt);
            }
        });
        getContentPane().add(TextEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 340, 40));

        EmailJLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        EmailJLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmailJLabel.setText("E-mail");
        getContentPane().add(EmailJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        EnderecoJLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        EnderecoJLabel.setForeground(new java.awt.Color(255, 255, 255));
        EnderecoJLabel.setText("Endereço");
        getContentPane().add(EnderecoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, -1, -1));

        TextEndereco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(TextEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 340, 40));

        BairrojLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        BairrojLabel.setForeground(new java.awt.Color(255, 255, 255));
        BairrojLabel.setText("Bairro");
        getContentPane().add(BairrojLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, -1, -1));

        TextBairro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextBairroActionPerformed(evt);
            }
        });
        getContentPane().add(TextBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 590, 340, 40));

        SenhaJLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        SenhaJLabel.setForeground(new java.awt.Color(255, 255, 255));
        SenhaJLabel.setText("Senha");
        getContentPane().add(SenhaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 660, -1, -1));

        TextSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(TextSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 680, 340, 40));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 750, 340, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/painelLongo.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 560, 800));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/papel-de-parede-adesivo-hamburgueria-preto.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 960));

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Usuário");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 570, -1, -1));

        Nome1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Nome1.setForeground(new java.awt.Color(255, 255, 255));
        Nome1.setText("Nome");
        getContentPane().add(Nome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEnderecoActionPerformed

    private void TextTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTelefoneActionPerformed

    private void TextNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TextCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCpfActionPerformed

    private void TextBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextBairroActionPerformed

    private void TextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BairrojLabel;
    private javax.swing.JLabel Cadastro;
    private javax.swing.JLabel CpfJLabel;
    private javax.swing.JLabel EmailJLabel;
    private javax.swing.JLabel EnderecoJLabel;
    private javax.swing.JLabel Nome1;
    private javax.swing.JLabel NomeJLabel;
    private javax.swing.JLabel SenhaJLabel;
    private javax.swing.JLabel TelefoneJLabel;
    private javax.swing.JTextField TextBairro;
    private javax.swing.JTextField TextCpf;
    private javax.swing.JTextField TextEmail;
    private javax.swing.JTextField TextEndereco;
    private javax.swing.JTextField TextNome;
    private javax.swing.JPasswordField TextSenha;
    private javax.swing.JTextField TextTelefone;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
