/*
 * To change this license header, choose License Headers id Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.MenuPedidoController;
import Model.Cliente;
import Model.Produto;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Snp
 */
public class MenuPedido extends javax.swing.JFrame {

    private final MenuPedidoController controller;

    /**
     * Creates new form MenuPedido
     */
    public MenuPedido() {
        initComponents();
        controller = new MenuPedidoController(this);
        iniciar(); 
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextoPedido = new javax.swing.JLabel();
        jIdLabel = new javax.swing.JLabel();
        TextId = new javax.swing.JTextField();
        nome = new javax.swing.JLabel();
        jComboboxCliente = new javax.swing.JComboBox<>();
        item1 = new javax.swing.JLabel();
        jComboboxProduto = new javax.swing.JComboBox<>();
        ValorjLabel = new javax.swing.JLabel();
        TextValor = new javax.swing.JTextField();
        ObservacaoLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextObservacao = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaPedidos = new javax.swing.JTable();
        jToggleButton2 = new javax.swing.JToggleButton();
        fundoTransparente = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextoPedido.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        TextoPedido.setForeground(new java.awt.Color(255, 255, 255));
        TextoPedido.setText("Pedido");
        getContentPane().add(TextoPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, -1, -1));

        jIdLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        jIdLabel.setText("Id");
        getContentPane().add(jIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        TextId.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TextId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextIdActionPerformed(evt);
            }
        });
        getContentPane().add(TextId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 340, 40));

        nome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nome.setForeground(new java.awt.Color(255, 255, 255));
        nome.setText("Cliente");
        getContentPane().add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        jComboboxCliente.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        getContentPane().add(jComboboxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 340, 40));

        item1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        item1.setForeground(new java.awt.Color(255, 255, 255));
        item1.setText("1- Item");
        getContentPane().add(item1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        jComboboxProduto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jComboboxProduto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboboxProdutoItemStateChanged(evt);
            }
        });
        jComboboxProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboboxProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboboxProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 340, 40));

        ValorjLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ValorjLabel.setForeground(new java.awt.Color(255, 255, 255));
        ValorjLabel.setText("Valor");
        getContentPane().add(ValorjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        TextValor.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        TextValor.setForeground(new java.awt.Color(0, 204, 0));
        TextValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorActionPerformed(evt);
            }
        });
        getContentPane().add(TextValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 340, 40));

        ObservacaoLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ObservacaoLabel1.setForeground(new java.awt.Color(255, 255, 255));
        ObservacaoLabel1.setText("Observação");
        getContentPane().add(ObservacaoLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

        TextObservacao.setColumns(20);
        TextObservacao.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        TextObservacao.setRows(5);
        jScrollPane1.setViewportView(TextObservacao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 620, 220));

        TabelaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "Cliente", "Pedido", "Observacao", "Valor"
            }
        ));
        jScrollPane2.setViewportView(TabelaPedidos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, 1000, 180));

        jToggleButton2.setBackground(new java.awt.Color(51, 51, 255));
        jToggleButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jToggleButton2.setText("Fechar Pedido");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 620, 70));

        fundoTransparente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/painelLongoOrizontal_1.png"))); // NOI18N
        fundoTransparente.setText("jLabel2");
        getContentPane().add(fundoTransparente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1140, 760));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/papel-de-parede-adesivo-hamburgueria-preto.jpg"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboboxProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboboxProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboboxProdutoActionPerformed

    private void jComboboxProdutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboboxProdutoItemStateChanged
        this.controller.atualizaValor();
    }//GEN-LAST:event_jComboboxProdutoItemStateChanged

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        this.controller.agendar();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void TextValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorActionPerformed

    private void TextIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPedido().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ObservacaoLabel1;
    private javax.swing.JTable TabelaPedidos;
    private javax.swing.JTextField TextId;
    private javax.swing.JTextArea TextObservacao;
    private javax.swing.JTextField TextValor;
    private javax.swing.JLabel TextoPedido;
    private javax.swing.JLabel ValorjLabel;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel fundoTransparente;
    private javax.swing.JLabel item1;
    private javax.swing.JComboBox<String> jComboboxCliente;
    private javax.swing.JComboBox<String> jComboboxProduto;
    private javax.swing.JLabel jIdLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel nome;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
        this.controller.atualizaTabelaPedido();
        this.controller.atualizaCliente();
        //this.controller.atualizaPedido();
        this.controller.atualizaProduto();
        this.controller.atualizaValor();
    }   

    public JTable getTabelaPedidos() {
        return TabelaPedidos;
    }

    public void setTabelaPedidos(JTable TabelaPedidos) {
        this.TabelaPedidos = TabelaPedidos;
    }

    public JComboBox<String> getjComboboxCliente() {
        return jComboboxCliente;
    }

    public void setjComboboxCliente(JComboBox<String> jComboboxCliente) {
        this.jComboboxCliente = jComboboxCliente;
    }
    //VERIFICAR CASO DE ERRO.
    public JComboBox<String> getjComboboxProduto() {
        return jComboboxProduto;
    }
    //VERIFICAR CASO DE ERRO.
    public void setjComboboxProduto(JComboBox<String> jComboboxProduto) {
        this.jComboboxProduto = jComboboxProduto;
    } 
    
    
    public JTextArea getjObservacaoTextArea1() {
        return TextObservacao;
    }

    public void setjObservacaoTextArea1(JTextArea jObservacaoTextArea1) {
        this.TextObservacao = jObservacaoTextArea1;
    }

    public JTextField getTextId() {
        return TextId;
    }

    public void setTextId(JTextField TextId) {
        this.TextId = TextId;
    }

    public JTextArea getTextObservacao() {
        return TextObservacao;
    }

    public void setTextObservacao(JTextArea TextObservacao) {
        this.TextObservacao = TextObservacao;
    }

    public JTextField getTextValor() {
        return TextValor;
    }

    public void setTextValor(JTextField TextValor) {
        this.TextValor = TextValor;
    }  
      
}
