/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.MenuPrincipalController;

/**
 *
 * @author Snp
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private final MenuPrincipalController controller;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.controller = new MenuPrincipalController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        MenuPrincipal = new javax.swing.JMenuBar();
        Cliente = new javax.swing.JMenu();
        CadastroCliente = new javax.swing.JMenuItem();
        ConsultaCliente = new javax.swing.JMenuItem();
        PedidoMenu = new javax.swing.JMenu();
        NovoPedido = new javax.swing.JMenuItem();
        ConsultarPedido = new javax.swing.JMenuItem();
        Produto = new javax.swing.JMenu();
        CadastroProduto = new javax.swing.JMenuItem();
        ConsultaProduto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/papel-de-parede-adesivo-hamburgueria-preto.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 770));

        Cliente.setForeground(new java.awt.Color(0, 51, 153));
        Cliente.setText("Cliente");
        Cliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        CadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Icons/cliente32-icon.png"))); // NOI18N
        CadastroCliente.setText("Cadastrar");
        CadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroClienteActionPerformed(evt);
            }
        });
        Cliente.add(CadastroCliente);

        ConsultaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Icons/relatorioTrabalho32-icon.png"))); // NOI18N
        ConsultaCliente.setText("Consultar");
        ConsultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaClienteActionPerformed(evt);
            }
        });
        Cliente.add(ConsultaCliente);

        MenuPrincipal.add(Cliente);

        PedidoMenu.setForeground(new java.awt.Color(0, 51, 153));
        PedidoMenu.setText("Pedido");
        PedidoMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        NovoPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Icons/Pedido3.png"))); // NOI18N
        NovoPedido.setText("Novo Pedido");
        NovoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoPedidoActionPerformed(evt);
            }
        });
        PedidoMenu.add(NovoPedido);

        ConsultarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Icons/bag_buy_cart_market_shop_shopping_tote_icon_123191.png"))); // NOI18N
        ConsultarPedido.setText("Consultar Pedido");
        ConsultarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarPedidoActionPerformed(evt);
            }
        });
        PedidoMenu.add(ConsultarPedido);

        MenuPrincipal.add(PedidoMenu);

        Produto.setForeground(new java.awt.Color(0, 51, 153));
        Produto.setText("Produto");
        Produto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        CadastroProduto.setText("Cadastrar");
        CadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroProdutoActionPerformed(evt);
            }
        });
        Produto.add(CadastroProduto);

        ConsultaProduto.setText("Consultar");
        Produto.add(ConsultaProduto);

        MenuPrincipal.add(Produto);

        setJMenuBar(MenuPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NovoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoPedidoActionPerformed
        this.controller.navegarParaPedido();
    }//GEN-LAST:event_NovoPedidoActionPerformed

    private void CadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroClienteActionPerformed
        this.controller.navegarParaCadastroUsuarios();
    }//GEN-LAST:event_CadastroClienteActionPerformed

    private void CadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastroProdutoActionPerformed

    private void ConsultarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarPedidoActionPerformed

    private void ConsultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaClienteActionPerformed
        this.controller.ConsultarUsuarios();
    }//GEN-LAST:event_ConsultaClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadastroCliente;
    private javax.swing.JMenuItem CadastroProduto;
    private javax.swing.JMenu Cliente;
    private javax.swing.JMenuItem ConsultaCliente;
    private javax.swing.JMenuItem ConsultaProduto;
    private javax.swing.JMenuItem ConsultarPedido;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JMenuItem NovoPedido;
    private javax.swing.JMenu PedidoMenu;
    private javax.swing.JMenu Produto;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
